name: Experiment

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Cache 📖
        uses: actions/cache@v2
        with:
          path: |
                ~/.julia/artifacts
                ~/.julia/packages
          key: ${{ runner.os }}-cacheB-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cacheB-

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      # Python
      - name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Python libs 🐍
        run: pip install matplotlib

      - run: |
             export PYTHON=$(which python);
             julia -e '
               using Pkg; Pkg.add(["PyCall", "PyPlot"]); Pkg.build("PyCall");
               using PyPlot;
               plot(rand(4), rand(4));
               println("OK");'
