name: Experiment

on:
  push:
    branches:
      - main

env:
  PYTHON_LIBS: "matplotlib pandas"

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Cache 📖
        uses: actions/cache@v2
        with:
          path: |
                ~/.julia/artifacts
                ~/.julia/packages
          key: ${{ runner.os }}-cacheB-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cacheB-

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      - if: ${{ env.PYTHON_LIBS != "" }}
        name: Install Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - if: ${{ env.PYTHON_LIBS != "" }}
        name: Installing Python packages 🐍
        run: pip install ${{ env.PYTHON_LIBS }}

      - run: |
             julia -e '
               using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall");
               Pkg.add("PyPlot"); using PyPlot;
               plot(rand(5), rand(5));
               println("OK");'
