name: Experiment

on:
  push:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Cache 📖
        uses: actions/cache@v2
        with:
          path: |
                ~/.julia/artifacts
                ~/.julia/packages
                !~/.julia/packages/PyPlot
                !~/.julia/packages/PyCall
                !~/.julia/packages/Conda
          key: ${{ runner.os }}-cache2-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache2-

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.7

      - run: |
             export PYTHON="";
             julia -e '
               using Pkg; Pkg.add("PyPlot");
               using PyPlot;
               plot(rand(6), rand(6));
               println("OK");'
